-- Tabela para armazenar as implantações (mapas de lotes)
CREATE TABLE IF NOT EXISTS implantacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imovel_id BIGINT REFERENCES imoveis(id) ON DELETE CASCADE,
    dados_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE implantacoes ENABLE ROW LEVEL SECURITY;

-- Política de leitura pública
CREATE POLICY "Permitir leitura pública de implantações" ON implantacoes FOR SELECT USING (true);

-- Política de escrita para teste
CREATE POLICY "Permitir escrita pública para teste" ON implantacoes FOR ALL WITH CHECK (true);
