-- SQL para criar a tabela de imóveis no Supabase
-- Copie e cole este código no SQL Editor do seu Dashboard do Supabase

CREATE TABLE IF NOT EXISTS imoveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    titulo TEXT NOT NULL,
    tipo TEXT,
    resumo TEXT,
    preco TEXT,
    imagem TEXT,
    selo TEXT,
    selo_classe TEXT,
    html_detalhes TEXT
);

-- Ativar o acesso público (Read-only por padrão, ou CRUD se quiser simplificar)
-- Nota: Em um ambiente de produção, você configuraria políticas de RLS (Row Level Security)
ALTER TABLE imoveis ENABLE ROW LEVEL SECURITY;

-- Política para permitir que qualquer pessoa leia os dados
CREATE POLICY "Permitir leitura pública" ON imoveis FOR SELECT USING (true);

-- Política para permitir inserção/alteração (Apenas para teste, ajuste depois!)
CREATE POLICY "Permitir inserção pública para teste" ON imoveis FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir alteração pública para teste" ON imoveis FOR UPDATE USING (true);
